### ISSUE TITLE
mat files is missing

### ISSUE THREAD

**Issue by xiaosnowqiang** [henriquepython/yolov2brasil#1]
**Hello sir，**
Could  you please upload the mat files：gTruth3.mat，trainingData，detector2.mat .
Thanks for your precious time !
**-Jian**

`Invalid file name detector2.mat. The file name must be
the name of a valid MAT file, or a valid function that
exists in the MATLAB path.`

**Comment by henriquedevnet** [comment]
Todos os arquivos estão presentes, os arquivos que estão faltando deve ser criado por você, pois são arquivos gerados apartir  das imagens do seu próprio dataset, e são arquivos pessoais.
